# Generated by Django 4.1.4 on 2023-04-22 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectInformation',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('repo1', models.URLField()),
                ('repo2', models.URLField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
